USE [master]  
GO  
  
/****** Object: Database [CustomerDB] Script Date: 9/25/2016 3:14:16 AM ******/  
CREATE DATABASE [CustomerDB]  
CONTAINMENT = NONE  
ON PRIMARY   
( NAME = N'CustomerDB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS12\MSSQL\DATA\CustomerDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )  
LOG ON   
( NAME = N'CustomerDB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS12\MSSQL\DATA\CustomerDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)  
GO  
  
ALTER DATABASE [CustomerDB] SET COMPATIBILITY_LEVEL = 110  
GO  
  
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))  
begin  
EXEC [CustomerDB].[dbo].[sp_fulltext_database] @action = 'enable'  
end  
GO  
  
ALTER DATABASE [CustomerDB] SET ANSI_NULL_DEFAULT OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET ANSI_NULLS OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET ANSI_PADDING OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET ANSI_WARNINGS OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET ARITHABORT OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET AUTO_CLOSE OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET AUTO_CREATE_STATISTICS ON   
GO  
  
ALTER DATABASE [CustomerDB] SET AUTO_SHRINK OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET AUTO_UPDATE_STATISTICS ON   
GO  
  
ALTER DATABASE [CustomerDB] SET CURSOR_CLOSE_ON_COMMIT OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET CURSOR_DEFAULT GLOBAL   
GO  
  
ALTER DATABASE [CustomerDB] SET CONCAT_NULL_YIELDS_NULL OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET NUMERIC_ROUNDABORT OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET QUOTED_IDENTIFIER OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET RECURSIVE_TRIGGERS OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET DISABLE_BROKER   
GO  
  
ALTER DATABASE [CustomerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET DATE_CORRELATION_OPTIMIZATION OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET TRUSTWORTHY OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET PARAMETERIZATION SIMPLE   
GO  
  
ALTER DATABASE [CustomerDB] SET READ_COMMITTED_SNAPSHOT OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET HONOR_BROKER_PRIORITY OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET RECOVERY SIMPLE   
GO  
  
ALTER DATABASE [CustomerDB] SET MULTI_USER   
GO  
  
ALTER DATABASE [CustomerDB] SET PAGE_VERIFY CHECKSUM   
GO  
  
ALTER DATABASE [CustomerDB] SET DB_CHAINING OFF   
GO  
  
ALTER DATABASE [CustomerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )   
GO  
  
ALTER DATABASE [CustomerDB] SET TARGET_RECOVERY_TIME = 0 SECONDS   
GO  
  
ALTER DATABASE [CustomerDB] SET READ_WRITE   
GO  